# Generated by Django 3.1 on 2020-08-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введіть назву статті', max_length=250, verbose_name='Назва статті')),
                ('author', models.CharField(help_text='Введіть назву статті', max_length=250, verbose_name='Автор статті')),
                ('pub_date', models.DateTimeField(help_text='Введіть дату публікації', verbose_name='Дата публікації')),
                ('text', models.TextField(help_text='Введіть текст статті', verbose_name='Текст статті')),
                ('likes', models.IntegerField(verbose_name='Кількість лайків')),
                ('dislikes', models.IntegerField(verbose_name='Кількість дизлайків')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть назву категорії', max_length=200)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text="Введіть ім'я автора коментаря", max_length=250, verbose_name='Автор коментаря')),
                ('text', models.TextField(help_text='Введіть текст статті', verbose_name='Текст коментаря')),
                ('pub_date', models.DateTimeField(help_text='Введіть дату публікації', verbose_name='Дата публікації')),
                ('likes', models.IntegerField(verbose_name='Кількість лайків')),
                ('dislikes', models.IntegerField(verbose_name='Кількість дизлайків')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'verbose_name': 'Кометар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть мову написання статті', max_length=200)),
            ],
            options={
                'verbose_name': 'Мова',
                'verbose_name_plural': 'Мови',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text="Введіть ім'я автора коментаря", max_length=250, verbose_name='Автор коментаря')),
                ('text', models.TextField(help_text='Введіть текст статті', verbose_name='Текст коментаря')),
                ('pub_date', models.DateTimeField(help_text='Введіть дату публікації', verbose_name='Дата публікації')),
                ('facebook', models.CharField(help_text='Введіть посилання на вашу сторінку Facebook', max_length=250, verbose_name='Ваша Facebook сторінка')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
            ],
            options={
                'verbose_name': 'Відповідь на коментар',
                'verbose_name_plural': 'Відповіді на коментар',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.language'),
        ),
    ]
