# Generated by Django 3.1 on 2020-08-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('Категорія',), 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.language'),
        ),
    ]
