# Generated by Django 3.1 on 2020-08-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200816_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('і',), 'verbose_name_plural': 'Категорії'},
        ),
    ]
