# Generated by Django 3.1 on 2020-08-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200816_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': ('Мова',), 'verbose_name_plural': 'Мови'},
        ),
    ]
