# Generated by Django 3.1 on 2020-08-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200816_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Мова', 'verbose_name_plural': 'Мови'},
        ),
    ]
