# Generated by Django 3.1 on 2020-08-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.SlugField(default='sample', max_length=130),
            preserve_default=False,
        ),
    ]
