# Generated by Django 3.1 on 2020-08-30 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200820_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Введіть дату публікації', verbose_name='Дата публікації'),
        ),
    ]
