# Generated by Django 3.1 on 2020-08-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200830_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
